### ISSUE TITLE
bug: It is incorrectly assumed that the user has installed typescript globally

### ISSUE THREAD

**Issue by Drincann** [yrming/vscode-type-challenges#15]
I realize that as long as I save an answer file, the status of the file will become complete, regardless of whether the implementation of the question is wrong.

After debugging, I found that because I have no reference to the tsc globally.

<img width="1514" alt="企业微信截图_1f4fecfa-8019-4eb0-94b6-e7730270643f" src="https://user-images.githubusercontent.com/53897259/209630539-2438322d-e075-4d5d-9dc2-b58198e87033.png">

**Comment by Drincann** [comment]
I don't know what is the best practice of installing npm dependencies for users in the vscode plugins.

**Comment by yrming** [comment]
@Drincann When checking the status of each challenge, the **tsc** command is used. This requires typescript to be installed globally. I will explain this in the readme, or I will add a reminder when command not found. Meanwhile, if you have a better way, please let me know.
