### ISSUE TITLE
<FeatureRequest> Light mode support; Syntax highlighting;

### ISSUE THREAD

**Issue by isunjn** [yrming/vscode-type-challenges#6]
Seemly like the color of font is hard-coded.

Also the syntax highlighting is missing for code blocks.

![x-220523-173128](https://user-images.githubusercontent.com/60461730/169790207-474d75da-381c-425f-af3c-21710fa6aa51.png)

**Comment by yrming** [comment]
Thanks. It will be supported soon.😀

**Comment by yrming** [comment]
@isunjn Hi, it is now supported. You can update to the latest version.
