### ISSUE TITLE
<FeatureRequest> Generate a tsconfig.json by default

### ISSUE THREAD

**Issue by isunjn** [yrming/vscode-type-challenges#7]
It's better to turn on some compiler flags by defalut.

For example, `strictNullChecks` is assumed by some test cases.

**Comment by yrming** [comment]
Let me think about it.

**Comment by yrming** [comment]
@isunjn Now it is supported, you can update to the latest version, sorry for it took so long. Hope you are still using this VSCode Extension.😃
