### ISSUE TITLE
Show the "completion" status in the sidebar tree

### ISSUE THREAD

**Issue by SimeonC** [yrming/vscode-type-challenges#8]
Seeing as we have the files on disk, it'd be nice to keep track of whether the relevant file for each challenge exists. This would help with keeping track of progress if you're like me and doing all the challenges in some order.

It'd be very cool if we could also show whether a started file has errors or is "complete/successful".

**Comment by yrming** [comment]
Thanks. It will be supported soon.😀

**Comment by yrming** [comment]
@SimeonC Hi, it is now supported. You can update to the latest version.

**Comment by SimeonC** [comment]
@yrming Thanks for the quick feature release! Works perfectly thanks!

**Comment by AngryChocobo** [comment]
My installed extension version is 1.5.0, but I can't see the status has changed. What  information can I provide to handle this problem ?

Oh, I am using Mac.  @yrming

**Comment by yrming** [comment]
@AngryChocobo Can you provide some screenshots?

**Comment by AngryChocobo** [comment]
> @AngryChocobo Can you provide some screenshots?

![error](https://user-images.githubusercontent.com/24283492/175313731-5646f9d3-a582-4c0d-9920-c86530dea141.gif)

**Comment by yrming** [comment]
@AngryChocobo I'll try to reproduce it, thanks a lot.

**Comment by yrming** [comment]
@AngryChocobo Open the developer tools (**Help** > **Toggle Developer Tools**) and check if there are any error messages.

**Comment by yrming** [comment]
@AngryChocobo By the way, do you have installed typescript globally?

**Comment by AngryChocobo** [comment]
> 

Looks like no error messages. Even after I click refresh button...

**Comment by AngryChocobo** [comment]
> @AngryChocobo By the way, do you have installed typescript globally?

I use `tsc -v` in iTerm2. It shows `Version 3.7.5`.

So I think I had install ts globally... Is it version engough ?

**Comment by yrming** [comment]
@AngryChocobo Please install latest version of TypeScript.

**Comment by AngryChocobo** [comment]
> 

![image](https://user-images.githubusercontent.com/24283492/178712473-851f02d3-82ee-48d6-a4e7-6c04aa4c874a.png)


QAQ
