### ISSUE TITLE
Completion status check is ignoring tsconfig.json

### ISSUE THREAD

**Issue by RomanKornev** [yrming/vscode-type-challenges#9]
Just noticed the new completion status feature in the sidebar. Thank you.

However, I noticed that if the project has a `tsconfig.json` file, there will be phantom status errors in the sidebar.
This is due to the fact that when specifying input files in `tsc`, the `tsconfig.json` is ignored. https://github.com/yrming/vscode-type-challenges/blob/d7d3eab34625aff0bcdc2088a12b71654ee68c10/src/utils/questions.ts#L123
As a result, the user will be left wondering why there are errors in the sidebar when the problems bar doesn't have any.
<img width="129" alt="image" src="https://user-images.githubusercontent.com/5807561/174456572-c265fe0a-6462-42dc-8705-c0128d9b21f2.png">
<img width="367" alt="image" src="https://user-images.githubusercontent.com/5807561/174456575-f23ecc57-328c-4171-9e84-b3ebaa5c6a98.png">
Is the correct way of using the extension to not have a `tsconfig.json` file at all?

**Comment by yrming** [comment]
@RomanKornev The default `tsconfig.json` has been added in the latest version, sorry for it took so long. Feel free to let me know if you have any questions.😃
